### ISSUE TITLE
does not work with Windows

### ISSUE THREAD

**Issue by tnguyen14** [springernature/hasbin#1]
I ran into this issue recently trying to debug an issue with using nature/pa11y with a colleague on a Windows machine. It fails because hasbin does not work on Windows.

The `PATH` env var on Windows is separated by semicolon `;` and not `:`, so it's being split at the wrong delimiter.

**Comment by rowanmanning** [comment]
Hi @tnguyen14, this should be fixed in `1.1.0` thanks to @moddular. Could you verify when you get a chance?
