### ISSUE TITLE
binaries in Windows 10 PATH entries with quotes return false when bin is present

### ISSUE THREAD

**Issue by mahopa** [springernature/hasbin#10]
Windows 10 added a new GUI when adding entries to the PATH variable that wraps path segments in quotes by default.

Binaries located under those quoted paths are missed by hasbin

I've forked the library and created a branch at [https://github.com/mahopa/hasbin/tree/pathQuotes](https://github.com/mahopa/hasbin/tree/pathQuotes) that should fix the issue. Let me know and I'll submit a pull request

**Comment by rowanmanning** [comment]
Excellent :) thanks Alex. I'll happily accept a PR if you want to open one

**Comment by rowanmanning** [comment]
Thanks again for reporting and providing a fix! I've released `1.2.3` with your changes.
