### ISSUE TITLE
hasbin.first

### ISSUE THREAD

**Issue by silverwind** [springernature/hasbin#3]
Small feature request: Find the first available binary, so something like this is possible:

``` js
hasbin.first(['vim', 'vi', 'nano', 'pico', 'ed'], function(binary) {
  // binary should be the name of the first available binary in the array
});
```

**Comment by rowanmanning** [comment]
Sure, happy to work on this. Will see when I have time. Also fine if you'd like to PR it :)

**Comment by moddular** [comment]
Hi - this has been added in hasbin 1.2.0 :)
